### ISSUE TITLE
源码中无com.riversoft.weixin.qy.base.DefaultSettings;

### ISSUE THREAD

**Issue by lqxion** [borball/weixin-sdk-demo#1]
clone这demo 更新pom.xml时在maven中央库中未发现0.5.1-SNAPSHOT版本 然后更新其它0.6.1版本WxCallbackController.java文件报找不到com.riversoft.weixin.qy.base.DefaultSettings;错误

**Comment by borball** [comment]
demo 基于老的SDK版本，不急的话等我更新到最新版本。

**Comment by borball** [comment]
demo has been updated to weixin-sdk 0.7.2, please get the latest code, feel free to close it if this can resolve your issue.

**Comment by lqxion** [comment]
ok！Thank you very much

**Comment by borball** [comment]
Updated to 0.8.2
